on:
  pull_request:
  push:
    branches: [main]
    tags: ["v*"]

env:
  DOTNET_VERSION: "6.0.x"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
      - uses: actions/setup-dotnet@55ec9447dda3d1cf6bd587150f3262f30ee10815 # v3.4.2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: install dotnet-format
        run: dotnet tool install -g dotnet-format --version 5.1.225507
      - name: lint
        working-directory: src
        run: dotnet format ActionsImporter.sln --verify-no-changes

  unit-test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
      - uses: actions/setup-dotnet@8e6bd2905eef86446227f003dda1deb3916c4aaf # v2.2.1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: dotnet restore
        run: dotnet restore src/ActionsImporter.sln
      - name: dotnet build
        run: dotnet build src/ActionsImporter.sln
      - name: dotnet test
        run: dotnet test src/ActionsImporter.UnitTests/ActionsImporter.UnitTests.csproj --no-build --no-restore --logger "junit;LogFilePath=unit-tests.xml"
      - name: publish test results
        uses: EnricoMi/publish-unit-test-result-action@d0a4676d0e0b938bc201470d88276b7c74c712b3 # v2.24.0
        if: always()
        with:
          files: "**/*-tests.xml"
          check_name: "Unit Test Results"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
      - uses: actions/setup-dotnet@55ec9447dda3d1cf6bd587150f3262f30ee10815 # v3.4.2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: dotnet restore
        run: dotnet restore src/ActionsImporter.sln
      - name: dotnet build
        run: dotnet build src/ActionsImporter.sln
      - name: Validate licenses
        run: |
          dotnet tool install --global ThirdLicense --version 1.2.0
          thirdlicense --project src/ActionsImporter.sln --output .licenses/new-licenses.txt
          diff -u .licenses/new-licenses.txt .licenses/licenses.txt
      - name: dotnet publish
        run: |
          dotnet publish src/ActionsImporter/ActionsImporter.csproj -c Release -r win10-x64 --self-contained -o dist/win-x64 --no-restore -p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true
          dotnet publish src/ActionsImporter/ActionsImporter.csproj -c Release -r osx-x64 --self-contained -o dist/osx-x64 --no-restore -p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true
          dotnet publish src/ActionsImporter/ActionsImporter.csproj -c Release -r osx-arm64 --self-contained -o dist/osx-arm64 --no-restore -p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true
          dotnet publish src/ActionsImporter/ActionsImporter.csproj -c Release -r linux-x64 --self-contained -o dist/linux-x64 --no-restore -p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true
      - name: prepare staging
        run: |
          mkdir -p ${{ runner.temp }}/staging
          cp dist/win-x64/gh-actions-importer.exe ${{ runner.temp }}/staging/actions-importer-windows-amd64.exe
          cp dist/osx-x64/gh-actions-importer ${{ runner.temp }}/staging/actions-importer-darwin-amd64
          cp dist/osx-arm64/gh-actions-importer ${{ runner.temp }}/staging/actions-importer-darwin-arm64
          cp dist/linux-x64/gh-actions-importer ${{ runner.temp }}/staging/actions-importer-linux-amd64

      - name: publish artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: actions-importer-${{ github.run_id }}
          path: ${{ runner.temp }}/staging/*

  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    environment: create_release
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
        with:
          fetch-depth: 0
      - name: validate tag on main
        shell: pwsh
        run: |
          git checkout main
          $mainsha = $(git show-ref refs/heads/main --hash)
          $tagsha = $(git show-ref ${{ github.ref }} --hash)
          Write-Output "refs/heads/main: $mainsha"
          Write-Output "${{ github.ref }}: $tagsha"
          if ($mainsha -ne $tagsha) {
            Write-Error "tag must match HEAD of main"
            exit 1
          }
      - name: download artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: actions-importer-${{ github.run_id }}
          path: ${{ runner.temp }}/dist
      - name: create release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        with:
          draft: true
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: |
            ${{ runner.temp }}/dist/actions-importer-windows-amd64.exe
            ${{ runner.temp }}/dist/actions-importer-linux-amd64
            ${{ runner.temp }}/dist/actions-importer-darwin-arm64
            ${{ runner.temp }}/dist/actions-importer-darwin-amd64
